language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
env:
  global:
    - secure: >-
        cxjsTZ4q96OMQOgofTwlOENMA58HYkMA+Ks0g+YuUq8F+LQS01VPx6cix+Ln1m9akjLUCC8TuJ+jLhHhtF/XauOh0akmbTrGLdfnO86edUn9Yig1Q/r6L0OIvTwmkV40thCyxJBaZxaG9lONG30UG9K2PmXteHhep4iUt/21P38o1iScUgmxH+i8wSeOLVvgU7tFEA0ulmvZNzOPB3OlHnmP1vBTYsN7osUqcuMCooIP1UG8aaq2FaTJ18Q6rb77KBqtKnlBYM5QhkBFWisYYCb9lw5jBkRYxJBwfJ3rWok4f5xsEnjiumBogg6xKOjRmOh1UmtRyeQV4LX2hJ+s6kh+N0mRad+maWeRv5rv1hDDfR6a1ZEJj6ITB70GdUuSUnL0iMlX+cTF6or6K9viQDaseRveNII/pgNP0Y9lZNVLmOb5bc4lo+b7n4BbmA9/5TVraVMG+TVz0tRb26hpnEF/i+WMBSsAtBp4NWdvKeKM0g1DYNRuqJ31I+0czgGZ3WfS+9nD7+VnXlfS5mok6WQI83JuPJiMSiJbU466Dcy+K+rLSyojP62Ov7wiX5cWI4LZRWc6xNpxq8DRVGm3z+1HMeaCCIjrg/FjsCl67zHhpeWUv6EX8/A8uCzP61xOFqn2qhCuW8vlOxILg9wf2mwXY+WR7vsQcDBJuadzwTU=
    - secure: >-
        t4Rn0lWCxzpapEvfwP7aPj/K7t+A4H7PR22hI9GzEuJqGM6Eqr7aNQNc481/yepfJZZacJBRN7eJF0EJrYuLJI/a1rCCD8zWDoJgiOjXHOGRXBnBvzRur5208MWyp+2pm/lYuZn3YezkzJT8C7CsKwdm4C+TPMXb7sGH8SklTB74Op2lVYeWrdMPnaJbuWXHp+xk75uWkHtYY1Frqk3FzJ3o/Jd7NSFHZICrKCx1EvUjO51wYUknPabqws30tuycrNsb1xXKp4o3XMweaGb7EBCBIwm2GuGY45uk8JvgVfeKgKnwFCWZrM4bUz3wfnSDcH/GQnBiXs9IyNlB72vKq3EG0lkv+V2R6h/+E99y3jmcv85eQ2qvBrovZ0zs9t7FsvYN+5QKUE1qxtqKtmgnMa28N4xZesWU5EsGMflmkACDvuSwk6uqe3minLoqHi2QsWtLbjHqPLnAPrV4vGEVwfSpchzPM3ZAezu7vrzF/Jnef65/xf9rJLFspAyUzyiHBNBGopVH7Hj+TOkUPhv0xI0qWQw/+aiRleM/N9fxvcM3hzbbAR50hQ8j5PwqGjwA/6411zaIt4xLf4JeqIUOhz4DqVvOsx1PJ/f+h5MyfTKP/w8fiTpBb/Bg4+VHw8W6u/FAbE0ggKD1nN0IP0sMSaNGuFMeEL44eORJvrVRt50=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
cache:
  directories:
    - node_modules
